import type { Metadata } from "next";
import { Lato } from 'next/font/google';

import "./globals.css";

const lato = Lato({
  subsets: ['latin'],
  weight: ['300', '400', '700', '900'], // choose what you need
  variable: '--font-lato',             // optional but recommended
});

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.variable}>
      <body>

        {children}

      </body>
    </html>
  );
}
